/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SetupMfaRouteImport } from './routes/setup-mfa'
import { Route as RequestAccessRouteImport } from './routes/request-access'
import { Route as MfaChallengeRouteImport } from './routes/mfa-challenge'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminDashboardRouteImport } from './routes/superadmin/dashboard'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated/contratos'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSectorsSlugRouteImport } from './routes/_authenticated/sectors.$slug'
import { Route as AuthenticatedContratosLotesRouteImport } from './routes/_authenticated/contratos/lotes'
import { Route as AuthenticatedContratosBacklogRouteImport } from './routes/_authenticated/contratos/backlog'

const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupMfaRoute = SetupMfaRouteImport.update({
  id: '/setup-mfa',
  path: '/setup-mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAccessRoute = RequestAccessRouteImport.update({
  id: '/request-access',
  path: '/request-access',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaChallengeRoute = MfaChallengeRouteImport.update({
  id: '/mfa-challenge',
  path: '/mfa-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminDashboardRoute = SuperadminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SuperadminRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSectorsSlugRoute =
  AuthenticatedSectorsSlugRouteImport.update({
    id: '/sectors/$slug',
    path: '/sectors/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContratosLotesRoute =
  AuthenticatedContratosLotesRouteImport.update({
    id: '/lotes',
    path: '/lotes',
    getParentRoute: () => AuthenticatedContratosRoute,
  } as any)
const AuthenticatedContratosBacklogRoute =
  AuthenticatedContratosBacklogRouteImport.update({
    id: '/backlog',
    path: '/backlog',
    getParentRoute: () => AuthenticatedContratosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/mfa-challenge': typeof MfaChallengeRoute
  '/request-access': typeof RequestAccessRoute
  '/setup-mfa': typeof SetupMfaRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/contratos': typeof AuthenticatedContratosRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/contratos/backlog': typeof AuthenticatedContratosBacklogRoute
  '/contratos/lotes': typeof AuthenticatedContratosLotesRoute
  '/sectors/$slug': typeof AuthenticatedSectorsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/mfa-challenge': typeof MfaChallengeRoute
  '/request-access': typeof RequestAccessRoute
  '/setup-mfa': typeof SetupMfaRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/contratos': typeof AuthenticatedContratosRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/contratos/backlog': typeof AuthenticatedContratosBacklogRoute
  '/contratos/lotes': typeof AuthenticatedContratosLotesRoute
  '/sectors/$slug': typeof AuthenticatedSectorsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/mfa-challenge': typeof MfaChallengeRoute
  '/request-access': typeof RequestAccessRoute
  '/setup-mfa': typeof SetupMfaRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/contratos': typeof AuthenticatedContratosRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/_authenticated/contratos/backlog': typeof AuthenticatedContratosBacklogRoute
  '/_authenticated/contratos/lotes': typeof AuthenticatedContratosLotesRoute
  '/_authenticated/sectors/$slug': typeof AuthenticatedSectorsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/complete-profile'
    | '/login'
    | '/mfa-challenge'
    | '/request-access'
    | '/setup-mfa'
    | '/superadmin'
    | '/admin'
    | '/app'
    | '/contratos'
    | '/auth/callback'
    | '/superadmin/dashboard'
    | '/contratos/backlog'
    | '/contratos/lotes'
    | '/sectors/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/complete-profile'
    | '/login'
    | '/mfa-challenge'
    | '/request-access'
    | '/setup-mfa'
    | '/superadmin'
    | '/admin'
    | '/app'
    | '/contratos'
    | '/auth/callback'
    | '/superadmin/dashboard'
    | '/contratos/backlog'
    | '/contratos/lotes'
    | '/sectors/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/change-password'
    | '/complete-profile'
    | '/login'
    | '/mfa-challenge'
    | '/request-access'
    | '/setup-mfa'
    | '/superadmin'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/contratos'
    | '/auth/callback'
    | '/superadmin/dashboard'
    | '/_authenticated/contratos/backlog'
    | '/_authenticated/contratos/lotes'
    | '/_authenticated/sectors/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
  LoginRoute: typeof LoginRoute
  MfaChallengeRoute: typeof MfaChallengeRoute
  RequestAccessRoute: typeof RequestAccessRoute
  SetupMfaRoute: typeof SetupMfaRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-mfa': {
      id: '/setup-mfa'
      path: '/setup-mfa'
      fullPath: '/setup-mfa'
      preLoaderRoute: typeof SetupMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-access': {
      id: '/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof RequestAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa-challenge': {
      id: '/mfa-challenge'
      path: '/mfa-challenge'
      fullPath: '/mfa-challenge'
      preLoaderRoute: typeof MfaChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/dashboard': {
      id: '/superadmin/dashboard'
      path: '/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof SuperadminDashboardRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sectors/$slug': {
      id: '/_authenticated/sectors/$slug'
      path: '/sectors/$slug'
      fullPath: '/sectors/$slug'
      preLoaderRoute: typeof AuthenticatedSectorsSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contratos/lotes': {
      id: '/_authenticated/contratos/lotes'
      path: '/lotes'
      fullPath: '/contratos/lotes'
      preLoaderRoute: typeof AuthenticatedContratosLotesRouteImport
      parentRoute: typeof AuthenticatedContratosRoute
    }
    '/_authenticated/contratos/backlog': {
      id: '/_authenticated/contratos/backlog'
      path: '/backlog'
      fullPath: '/contratos/backlog'
      preLoaderRoute: typeof AuthenticatedContratosBacklogRouteImport
      parentRoute: typeof AuthenticatedContratosRoute
    }
  }
}

interface AuthenticatedContratosRouteChildren {
  AuthenticatedContratosBacklogRoute: typeof AuthenticatedContratosBacklogRoute
  AuthenticatedContratosLotesRoute: typeof AuthenticatedContratosLotesRoute
}

const AuthenticatedContratosRouteChildren: AuthenticatedContratosRouteChildren =
  {
    AuthenticatedContratosBacklogRoute: AuthenticatedContratosBacklogRoute,
    AuthenticatedContratosLotesRoute: AuthenticatedContratosLotesRoute,
  }

const AuthenticatedContratosRouteWithChildren =
  AuthenticatedContratosRoute._addFileChildren(
    AuthenticatedContratosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRouteWithChildren
  AuthenticatedSectorsSlugRoute: typeof AuthenticatedSectorsSlugRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedContratosRoute: AuthenticatedContratosRouteWithChildren,
  AuthenticatedSectorsSlugRoute: AuthenticatedSectorsSlugRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SuperadminRouteChildren {
  SuperadminDashboardRoute: typeof SuperadminDashboardRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminDashboardRoute: SuperadminDashboardRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  CompleteProfileRoute: CompleteProfileRoute,
  LoginRoute: LoginRoute,
  MfaChallengeRoute: MfaChallengeRoute,
  RequestAccessRoute: RequestAccessRoute,
  SetupMfaRoute: SetupMfaRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
